target-version = "py312"
line-length = 99

[lint]
select = ["E", "F", "W", "I", "N", "UP", "B", "A", "SIM"]
ignore = ["E501"]

[lint.isort]
known-first-party = ["app"]

[format]
quote-style = "double"
indent-style = "space"
